trigger BookingTrigger on Booking__c (after insert,before update) {
    if(trigger.isinsert)
    {
        if(trigger.isAfter)
        {
            BookingTriggerHandler.afterInsert(trigger.new);
        }
    }
    if(trigger.isUpdate)
    {
        if(trigger.isBefore)
        {
            BookingTriggerHandler.beforeUpdate(trigger.new,trigger.oldMap);
        }
        else
        {
            BookingTriggerHandler.afterUpdate(trigger.new,trigger.oldMap);
        }
    }
}