/****************************************************************
* Class Name   : WebsiteAPIController
* Company      : Fingertipplus
* Created Date : 20-05-2025
* @description : This class is used for Integration with website for Capturing the Lead into Salesforce 
* @author      : Praveen Kumar

* Change Log:
* -----------------------------------------------------------------------------
* Ver | Author 			| 	  Date 		| Description
* -----------------------------------------------------------------------------
* 1.0 | Praveen Kumar 	| 20-05-2025 	| Initial version
* 2.0 | Mayuri Patel 	| 20-10-2025 	| Modified Version with updated field names for Source/Sub Source
* 3.0 | Mayuri Patel 	| 06-11-2025 	| Added campaign parameters
* -----------------------------------------------------------------------------
**************************************************************/
@RestResource(urlMapping='/WebsiteLead/*')
global without sharing class WebsiteAPIController {
    @HttpPost
    global static void createLead() {
        RestRequest req = RestContext.request;
        String requestBody = req.requestBody.toString(); // Get the JSON body
        Apex_Log__c log = new Apex_Log__c();
        log.Request_Type__c ='WebsiteAPIController '+' WebsiteLead';
        
        try {
            // Deserialize the JSON body into the callWrapper class
            leadWrapper ldData = (leadWrapper) JSON.deserialize(requestBody, leadWrapper.class);
            log.Request__c=requestBody;
            // Create a new Lead using the deserialized data
            Lead nld = new Lead();
            nld.FirstName = ldData.firstName;
            nld.LastName = ldData.lastName;
            nld.Source_Type__c = ldData.source;
            nld.Lead_source__c = ldData.subSource;
            nld.Sub_Source__c = ldData.subSource;
            nld.Phone = ldData.mobile;
            nld.Phone__c = ldData.mobile;
            nld.Email = ldData.email;
            nld.Allocated_project__c = ldData.project;
            nld.Description = ldData.description;
            //nld.Campaign__c = ldData.campaign;
            
            List<Campaign> cmp = new List<Campaign>();
            if(ldData.campaignId != null){
                cmp = [select Id,Name,Project_Name__c,Source__c,Sub_Source__c,Ad_Name__c,Ad_Set_Name__c from Campaign where Campaign_Id__c = :ldData.campaignId and IsActive = true order by createddate desc limit 1];
            }
            else if(ldData.campaignId == null && ldData.campaignName != null){
                cmp = [select Id,Name,Project_Name__c,Source__c,Sub_Source__c,Ad_Name__c,Ad_Set_Name__c from Campaign where Name = :ldData.campaignName and IsActive = true order by createddate desc limit 1];
            }
            if(cmp.size() > 0){
                nld.Campaign_std__c = cmp[0].Id;
                nld.Campaign__c = cmp[0].Name;
                nld.Source_Type__c = cmp[0].Source__c;
                nld.Lead_source__c = cmp[0].Sub_Source__c;
                nld.Sub_Source__c =  cmp[0].Name;
                nld.Campaign_Ad_Name__c = cmp[0].Ad_Name__c;
                nld.Campaign_Ad_Set_Name__c = cmp[0].Ad_Set_Name__c;
            }
               
            insert nld;
            // Return success response
            log.response__c = string.valueof(nld);
            log.Status__c ='SUCCESS';
            insert log;
            
            RestContext.response.statusCode = 200;
            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(new Map<String, Object>{
                'success' => true,
                    'Salesforce LeadId' => nld.Id
                    }));
        } catch (Exception e) {
            log.response__c = e.getStackTraceString();
            log.Status__c ='FAIL';
            log.Error_Message__c = e.getMessage();
            insert log;
            
            System.debug('Error creating task: ' + e.getMessage());
            RestContext.response.statusCode = 400;
            RestContext.response.responseBody = Blob.valueOf('Error: ' + e.getMessage());
        }
    }
    
    // Wrapper class for deserialization
    public class leadWrapper {
        public String firstName;
        public String lastName;
        public String source;
        public String subSource;
        public String mobile;
        public String email;
        public String project;
        public String unitPreference;
        public String campaign;
        public String campaignId;
        public String campaignName;
        public String cpId;
        public String cpName;
        public String cpPhone;
        public String description;
        /*public String residencelocation;
        public String worklocation;
        public String hearaboutus;
        public String utmSource;
        public String utmMedium;
        public String utmCampaign;
        public String utmAdgroup;
        public String utmTerm;
        public String utmPlacment;
        public String utmDevice;*/
    }
    
           /* if(ldData.source =='MagicBricks'|| ldData.source =='99 Acres' || ldData.source =='Housing.com'){
                nld.Source_Type__c ='Digital Marketing';
                nld.Lead_source__c ='Real Estate Portals';
                nld.Tertiary_Source__c =ldData.source;
                
            }
            if(ldData.source =='Website'){
                nld.Source_Type__c ='Digital Marketing';
                nld.Lead_source__c ='Website';
                nld.Tertiary_Source__c = 'Microsite';
                
            }
            if(ldData.source =='GoogleSearch'|| ldData.source =='GoogleDemandgen' || ldData.source =='FacebookCTW'|| ldData.source =='Taboola'){
                nld.Source_Type__c ='Digital Marketing';
                nld.Lead_source__c =ldData.source;
               // nld.Tertiary_Source__c = 'NA';
                
            }*/
            // nld.Source_Type__c='Digital';
            /*nld.UTM_Source__c = ldData.utmSource;
            nld.UTM_Medium__c = ldData.utmMedium;
            nld.UTM_Campaign__c = ldData.utmCampaign;
            nld.UTM_Adgroup__c = ldData.utmAdgroup;
            nld.UTM_Term__c = ldData.utmTerm;
            nld.UTM_Placement__c = ldData.utmPlacment;
            nld.UTM_Device__c = ldData.utmDevice;*/
    
}